{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: shop-ingress
  labels:
spec:
  rules:
    - host: {{ .Values.shopWeb.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.shopWeb.ingress.path | quote }}
            backend:
              serviceName: shop-web-service
              servicePort: {{ .Values.shopWeb.service.port }}