apiVersion: v1
kind: Secret
metadata:
  name:  mongodb-secret
type: Opaque
data:
  MONGO_HOST: {{ include "demo.mongodb.host" . | b64enc | quote }}
  {{- if .Values.mongodb.mongodbDatabase }}
  MONGO_DB: {{ .Values.mongodb.mongodbDatabase | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.mongodbUsername }}
  MONGO_USER: {{ .Values.mongodb.mongodbUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.mongodbPassword }}
  MONGO_PASS: {{ .Values.mongodb.mongodbPassword | b64enc | quote }}
  {{- end }}
