apiVersion: v1
kind: Secret
metadata:
  name:  redis-secret
type: Opaque
data:
  REDIS_HOST: {{ include "demo.redis.host" . | b64enc | quote }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
