apiVersion: v1
kind: Secret
metadata:
  name:  mysql-secret
type: Opaque
data:
  MYSQL_HOST: {{ include "demo.mysql.host" . | b64enc | quote }}
  MYSQL_TABLE: b3JkZXJfcGF5X2luZm8=
  {{- if .Values.mysql.mysqlDatabase }}
  MYSQL_DB: {{ .Values.mysql.mysqlDatabase | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.mysqlUser }}
  MYSQL_USER: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.mysqlPassword }}
  MYSQL_PASS: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  {{- end }}
