apiVersion: v1
kind: Service
metadata:
  name: shop-web-service
spec:
  type: {{ .Values.shopWeb.service.type }}
  ports:
    - port: {{ .Values.shopWeb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "demo.name" . }}
    app.kubernetes.io/instance: shop-web